name = "Telomerase"
author = "FaceTorched, Yeahminecraft16, Jerome226"
version = "1.20.4-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f00e623a99e4847ed63ef5eca27e5dadeaab0672a69dc519f86d6ce68d8c8387"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
