name = "Telomerase"
author = "FaceTorched, Yeahminecraft16, Jerome226"
version = "1.20.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b0e6a9554006c39d6fe7833e9c726f0bd1807bb5048c8ac2c29e2f415b7f623"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
