name = "Telomerase"
author = "FaceTorched, Yeahminecraft16, Jerome226"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24183de70276a38274c00dd7456cf826c6e77b2003c137ed1b12803ca1481918"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
