name = "Telomerase"
author = "FaceTorched, Yeahminecraft16, Jerome226"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13f4926c54c74915901b1d4afa95d84c2e9f7a6a82b1441c92d0fd562ee3a975"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
