name = "Telomerase"
author = "FaceTorched, Yeahminecraft16, Jerome226"
version = "1.20.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ffabf723eef560e9e6b566fe04e2b6b15500534e7dfdd17d4d53e99a2054001"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
