name: build

on:
  pull_request:
  push:
    branches:
      - main
      - build-workflows

jobs:
  curse:
    name: Build and Package
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
          go-version: 1.24.1
    - run: go install github.com/packwiz/packwiz@latest

    # Create the CurseForge pack
    - run: packwiz cf install filedirector
    - run: packwiz cf export

    # Create Modrinth pack
    - run: packwiz mr install filedirector
    - run: packwiz mr export

    # Create the server pack
    - run: .\CreateServerPack.bat

    # upload all files
    - uses: actions/upload-artifact@v4
      with:
        name: all-modpacks
        path: |
            ./*.zip
            ./*.mrpack
