name: build

on:
  pull_request:
  push:
    branches:
      - main
      - build-workflows

jobs:
  curse:
    name: Curseforge
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
          go-version: 1.24.1
    - run: go install github.com/packwiz/packwiz@latest
    - run: packwiz cf export
    - uses: actions/upload-artifact@v4
      with:
        name: curseforge-artifact
        path: ./*.zip
  modrinth:
    name: Modrinth
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
            go-version: 1.24.1
    - run: go install github.com/packwiz/packwiz@latest
    - run: packwiz mr install filedirector
    - run: packwiz mr export
    - uses: actions/upload-artifact@v4
      with:
        name: modrinth-artifact
        path: ./*.mrpack
  server:
    name: Server
    runs-on: windows-latest
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
    - run: .\CreateServerPack.bat
    - uses: actions/upload-artifact@v4
      with:
        name: server-artifact
        path: ./*.zip